from functools import partial


def get_permissions():
    """
    Returns a dictionary of all permissions for the pagemanager
    model. Keys are short names, values are full names.
    """
    from pagemanager.util import get_pagemanager_model
    page_model = get_pagemanager_model()
    # Create a list of permissions defined in the model...
    perms = [k for k, v in page_model._meta.permissions]
    # ... and add the standard Django permissions to it.
    perms.append(page_model._meta.get_add_permission())
    perms.append(page_model._meta.get_change_permission())
    perms.append(page_model._meta.get_delete_permission())
    app_label = page_model._meta.app_label
    return dict(
        [(key, "%s.%s" % (app_label, key)) for key in perms]
    )


def get_lookup_function(user=None, permission_list=None):
    """
    Given a user an list of permissions (like the one generated by
    the ``get_permissions`` function above) this returns a function which
    takes a permission name and returns a boolean value indicating whether
    the user has the given permission.
    """
    def _lookup_func(user, permission_list, permission_name):
        return user.has_perm(permission_list[permission_name])
    return partial(_lookup_func, user, permission_list)

# Below, the business logic for whether a page is public or published is
# encapsulated in a single location. This info will be needed in
# multiple places throughout the pagemanager application. These functions
# are the canonical method for determining what consititutes "public" and
# "published"!


def get_published_status_name():
    """
    Gets the value stored for a status of "published".
    Always assumes the final status choice is the one that means 'published'.
    """
    from pagemanager.util import get_pagemanager_model
    page_model = get_pagemanager_model()
    return page_model._meta.get_field('status').choices[-1][0]


def get_unpublished_status_name():
    """
    Gets an unpublished status.
    Always assumes the first status choice is the one that means
    'not published'.
    """
    from pagemanager.util import get_pagemanager_model
    page_model = get_pagemanager_model()
    return page_model._meta.get_field('status').choices[0][0]


def get_public_visibility_name():
    """
    Gets the value stored for a visibility of "public".
    Always assumes the first visibility choice is the one that means
    'public'.
    """
    from pagemanager.util import get_pagemanager_model
    page_model = get_pagemanager_model()
    return page_model._meta.get_field('visibility').choices[0][0]
