from functools import partial
from pagemanager.util import get_pagemanager_model

def get_permissions():
    """
    Returns a dictionary of all permissions for the pagemanager
    model. Keys are short names, values are full names.
    """
    page_model = get_pagemanager_model()
    # Create a list of permissions defined in the model...
    perms = [k for k, v in page_model._meta.permissions]
    # ... and add the standard Django permissions to it.
    perms.append(page_model._meta.get_add_permission())
    perms.append(page_model._meta.get_change_permission())
    perms.append(page_model._meta.get_delete_permission())
    app_label = page_model._meta.app_label
    return dict(
        [(key, "%s.%s" % (app_label, key)) for key in perms]
    )

def get_lookup_function(user=None, permission_list=None):
    """
    Given a user an list of permissions (like the one generated by 
    the ``get_permissions`` function above) this returns a function which
    takes a permission name and returns a boolean value indicating whether
    the user has the given permission.
    """
    def _lookup_func(user, permission_list, permission_name):
        return user.has_perm(permission_list[permission_name])
    return partial(_lookup_func, user, permission_list)